---
- hosts: all
  become: yes
  become_user: root
  vars_files:
    - settings.yml
  tasks:
    - import_role:
        name: basic
    - import_role:
        name: virtual_box
##    - import_role:
##        name: cntlm
##    - import_role:
##        name: docker
    - import_role:
        name: gui_gnome
    - import_role:
        name: gui_terminator
    - import_role:
        name: developer_basic
    - import_role:
        name: developer_gui
##    - import_role:
##        name: java_developer_basic
##    - import_role:
##        name: java_developer_gui
##    - import_role:
##        name: python_developer_basic
##    - import_role:
##        name: python_developer_gui
