# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1611.01"
  
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true

     vb.cpus = 4
     vb.memory = "2048"
          
     vb.customize ["modifyvm", :id, "--clipboard",   "bidirectional"]
     vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"] 
     vb.customize ["modifyvm", :id, "--vram", "128"]
   end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
