- name: Change default keyboard to {{ keyboard_language }}
  lineinfile:
    path: /etc/vconsole.conf
    regexp: '^KEYMAP="us"$'
    line: 'KEYMAP="{{ keyboard_language }}"'
- name: Install epel release
  yum: 
    name: "epel-release"
    state: present
